name: CI

on:
  pull_request:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .docs/
    permissions:
      actions: none
      checks: none
      contents: read
      deployments: none
      issues: none
      packages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Set up Node.js 12.X"
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '12.x'
      
      - name: "Install all dependencies"
        run: npm ci

      - name: "Run build"
        run: npm run build